### ISSUE TITLE
Traceback prevents startup on Fedora 20

### ISSUE THREAD

**Issue by nekohayo** [projecthamster/hamster#145]
Hi! I decided to give my long lost friend, Hamster, a try today. Checked out git master and looked at the README, which kinda scared me into grabbing the 1.0.4 tarball instead. I extracted the tarball, ran /waf configure build --prefix=/usr && sudo ./waf install

Trying to run "hamster" results in:

```
jeff@krimson:~$ hamster 
WARNING:root:Could not import wnck - workspace tracking will be disabled
Traceback (most recent call last):
  File "/usr/bin/hamster", line 374, in <module>
    hamster_client.today()
  File "/usr/bin/hamster", line 136, in today
    app = today.DailyView()
  File "/usr/lib/python2.7/site-packages/hamster/today.py", line 90, in __init__
    self.create_hamster_window()
  File "/usr/lib/python2.7/site-packages/hamster/today.py", line 154, in create_hamster_window
    self.new_tags = widgets.TagsEntry()
  File "/usr/lib/python2.7/site-packages/hamster/widgets/tags.py", line 65, in __init__
    self.populate_suggestions()
  File "/usr/lib/python2.7/site-packages/hamster/widgets/tags.py", line 152, in populate_suggestions
    self.tags = self.tags or [tag["name"] for tag in runtime.storage.get_tags(only_autocomplete=True)]
  File "/usr/lib/python2.7/site-packages/hamster/client.py", line 145, in get_tags
    return self._to_dict(('id', 'name', 'autocomplete'), self.conn.GetTags(only_autocomplete))
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlite3.OperationalError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/hamster-time-tracker/hamster-service", line 284, in GetTags
    return [(tag['id'], tag['name'], tag['autocomplete']) for tag in self.get_tags(only_autocomplete)]
  File "/usr/lib/python2.7/site-packages/hamster/storage.py", line 153, in get_tags
    return self.__get_tags(only_autocomplete)
  File "/usr/lib/python2.7/site-packages/hamster/db.py", line 156, in __get_tags
    return self.fetchall("select * from tags where autocomplete != 'false' order by name")
  File "/usr/lib/python2.7/site-packages/hamster/db.py", line 900, in fetchall
    cur.execute(query)
OperationalError: no such table: tags
```

I tried moving ~/.gnome2/hamster* and ~/.local/share/hamster* out of the way just in case, no luck.

**Comment by toupeira** [comment]
Closing this, feel free to reopen if you still experience this issue with current master.
