### ISSUE TITLE
Process /usr/lib/hamster-time-tracker/hamster-service exited with status 1

### ISSUE THREAD

**Issue by nchevobbe** [projecthamster/hamster#165]
Hi,

I tried to install the 1.0.4 version on a fresh ubuntu 14.04 install, but when launching hamster i got this error :

```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 374, in <module>
    hamster_client.today()
  File "/usr/bin/hamster", line 136, in today
    app = today.DailyView()
  File "/usr/lib/python2.7/dist-packages/hamster/today.py", line 90, in __init__
    self.create_hamster_window()
  File "/usr/lib/python2.7/dist-packages/hamster/today.py", line 148, in create_hamster_window
    self.new_name = widgets.ActivityEntry()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 103, in __init__
    self.populate_suggestions()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 234, in populate_suggestions
    self.activities = runtime.storage.get_activities(fact.activity)
  File "/usr/lib/python2.7/dist-packages/hamster/client.py", line 137, in get_activities
    return self._to_dict(('name', 'category'), self.conn.GetActivities(search))
  File "/usr/lib/python2.7/dist-packages/hamster/client.py", line 88, in conn
    '/org/gnome/Hamster'),
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/lib/hamster-time-tracker/hamster-service exited with status 1
```

Does anyone knows what's wrong ?

Thank you

**Comment by abraxxa** [comment]
For me just removing the storage directory worked.

**Comment by sabrefm1** [comment]
im currently running 18.04 as well but wasnt able to get the inidicator on the top tray working

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.
