### ISSUE TITLE
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply

### ISSUE THREAD

**Issue by umpirsky** [projecthamster/hamster#220]
I just installed hamster-time-tracker-1.04 and when I run it:

```
$ hamster
Traceback (most recent call last):
  File "/usr/local/bin/hamster", line 374, in <module>
    hamster_client.today()
  File "/usr/local/bin/hamster", line 136, in today
    app = today.DailyView()
  File "/usr/local/lib/python2.7/dist-packages/hamster/today.py", line 90, in __init__
    self.create_hamster_window()
  File "/usr/local/lib/python2.7/dist-packages/hamster/today.py", line 148, in create_hamster_window
    self.new_name = widgets.ActivityEntry()
  File "/usr/local/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 103, in __init__
    self.populate_suggestions()
  File "/usr/local/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 234, in populate_suggestions
    self.activities = runtime.storage.get_activities(fact.activity)
  File "/usr/local/lib/python2.7/dist-packages/hamster/client.py", line 137, in get_activities
    return self._to_dict(('name', 'category'), self.conn.GetActivities(search))
  File "/usr/local/lib/python2.7/dist-packages/hamster/client.py", line 88, in conn
    '/org/gnome/Hamster'),
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by FelixSchwarz** [comment]
I guess there is an exception in one of the two hamster daemons. can you try running "python2 /usr/bin/hamster-service" and "python2 /usr/bin/hamster-windows-service" from the shell?

**Comment by umpirsky** [comment]
@FelixSchwarz I am not using the app any more, and I reinstalled my system since then. I am not sure if it is still relevant?

**Comment by FelixSchwarz** [comment]
well, in that case just close this bug report please. Your original report is likely about a real bug but without further investigation we won't find out what it was.

**Comment by umpirsky** [comment]
OK, sure. Thanks.
