### ISSUE TITLE
accidentally referenced nonexisting .ui-files

### ISSUE THREAD

**Issue by auipga** [projecthamster/hamster#231]
installed with
```
./waf configure build --prefix=/usr
sudo ./waf install
```
somewhere in the code the file 'overview.ui' is referenced although was removed in https://github.com/projecthamster/hamster/commit/7e4863eb1b8046a417e7cc2e6f2bed370ef96bca seems still to be in use.

Running hamster results in:
```
Traceback (most recent call last):
  File "/usr/sbin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/sbin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/sbin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.glib.GError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/hamster-time-tracker/hamster-windows-service", line 38, in overview
    def overview(self): dialogs.overview.show(self.app)
  File "/usr/lib/python2.7/site-packages/hamster/configuration.py", line 106, in show
  File "/usr/lib/python2.7/site-packages/hamster/overview.py", line 51, in __init__
  File "/usr/lib/python2.7/site-packages/hamster/configuration.py", line 156, in load_ui_file
GError: Failed to open file '/usr/share/hamster-time-tracker/overview.ui': No such file or directory
```

**Comment by auipga** [comment]
seems to be fixed. no errors anymore with latest master
