### ISSUE TITLE
Startup fails with error

### ISSUE THREAD

**Issue by Uriziel** [projecthamster/hamster#245]
Starting up fails with the following error
    Traceback (most recent call last):
      File "/usr/local/bin/hamster", line 387, in <module>
        hamster_client.overview()
      File "/usr/local/bin/hamster", line 152, in overview
        self._launch_window("overview")
      File "/usr/local/bin/hamster", line 143, in _launch_window
        getattr(server, window_name)()
      File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
        return self._proxy_method(*args, **keywords)
      File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
        **keywords)
      File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
        message, timeout)
    dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ZeroDivisionError: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
        retval = candidate_method(self, *args, **keywords)
      File "/usr/local/lib/hamster-time-tracker/hamster-windows-service", line 38, in overview
        def overview(self): dialogs.overview.show(self.app)
      File "/usr/local/lib/python2.7/dist-packages/hamster/lib/configuration.py", line 149, in show
        dialog = self.get_dialog_class()(parent, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/hamster/overview.py", line 418, in __init__
        self.find_facts()
      File "/usr/local/lib/python2.7/dist-packages/hamster/overview.py", line 456, in find_facts
        self.totals.set_facts(self.facts)
      File "/usr/local/lib/python2.7/dist-packages/hamster/overview.py", line 306, in set_facts
        self.stacked_bar.set_items([(cat, delta.total_seconds() / 60.0) for cat, delta in totals['category']])
      File "/usr/local/lib/python2.7/dist-packages/hamster/overview.py", line 137, in set_items
        res.append((key, val, val * 1.0 / max_value))
    ZeroDivisionError: float division by zero

**Comment by Newman101** [comment]
Hi. I tried to replicate the error. It seems to be working on Ubuntu LTS 14.04 / Python 3.4. Can you provide more details, please? 

On the initial look it seems to be that max_value == 0.

**Comment by rapgro** [comment]
This issue is about Python 2.7, look in the pathes of the backtrace. 
Is there official support for Python 3.x?

**Comment by GCorbel** [comment]
I have the same issue and the solution provided in the PR works but it have to be merged.

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.
There is no official python 3 support for *legacy hamster*. I personally do not have time to test this PR as I sink all thats available into the new version. If anyone could test the PR against python 2 *and* 3 and confirm it works I think I would be inclined to merge it in order to make live easier with *legacy hamster* until we release the new version.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by GCorbel** [comment]
I rolled back to the latest stable version and it works. I will wait for the next version.
