### ISSUE TITLE
Error on startup after upgrading to Ubuntu 15.10

### ISSUE THREAD

**Issue by gsmetal** [projecthamster/hamster#263]
I've just upgraded to Ubuntu 15.10 and now installed hamster is not starting with error:

```
$ hamster
Traceback (most recent call last):
  File "/usr/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.175 was not provided by any .service files
```

I've tried to reinstall it with no luck.

**Comment by Chouchen** [comment]
Same here, and when I try launching with : 
```
user:~$ /usr/lib/hamster-time-tracker/hamster-service
``` 
I got 
``` 
hamster-service up
segfault (core dumped)
```

**Comment by Chouchen** [comment]
Alright, it works for me now. Here's how I did it :
 - `sudo apt-get --purge remove hamster`
 - I had to remove some folders that `remove` couldn't delete :  `sudo rm -r /usr/lib/python2.7/dist-packages/hamster/`
 - I also used `sudo apt-get --purge autoremove` because I tried to install the old hamster-applet too...
 - I installed waf ( https://waf.io/book/#_download_and_installation ) : 
``` 
wget https://waf.io/waf-1.8.16
mv waf-1.8.16 waf
python waf --version
```
 - then :

``` 
git clone https://github.com/projecthamster/hamster.git
cd hamster/
./waf configure build --prefix=/usr/local
sudo ./waf install
```
And now it works

**Comment by cutalion** [comment]
I repeated @Chouchen's steps with no luck. Successfully compiled and installed. 
```
Traceback (most recent call last):
  File "/usr/local/bin/hamster", line 30, in <module>
    from hamster import client, reports
  File "/usr/local/lib/python2.7/dist-packages/hamster/reports.py", line 32, in <module>
    from hamster.lib.configuration import runtime
  File "/usr/local/lib/python2.7/dist-packages/hamster/lib/configuration.py", line 33, in <module>
    from gi.repository import GConf as gconf
ImportError: cannot import name GConf
```

Ubuntu 15.10 fresh install

**Comment by toupeira** [comment]
@cutalion did you install the dependencies `python-gconf` and `gir1.2-gconf-2.0` as described in the README?

**Comment by Chouchen** [comment]
I updated my answer as I forgot those dependencies (which are required whatever the way you install hamster)

**Comment by cutalion** [comment]
Thanks, I've recompiled hamster. Now there is another exception.
```
Traceback (most recent call last):
  File "/usr/local/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/local/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/local/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.195 was not provided by any .service files
```

**Comment by cutalion** [comment]
I can run python console, import dbus and test this code, actually. Except I don't know what should it be if not exception.

```
            window_name = "overview"

            import dbus
            bus = dbus.SessionBus()
            server = bus.get_object("org.gnome.Hamster.WindowServer",
                                    "/org/gnome/Hamster/WindowServer")
            getattr(server, window_name)()
```

I'm getting the same exception from console too.

**Comment by cutalion** [comment]
I installed DFeet to check objects in DBus. There are no `org.gnome.Hamster*` paths.
![d-feet screenshot](https://cloud.githubusercontent.com/assets/103887/11085243/0c1b7490-8855-11e5-8596-9968b4495243.png)

**Comment by cutalion** [comment]
Sorry, this screenshot was made after I killed hamster-windows-server.
After run hamster I can see it. But I still get exception

```
Traceback (most recent call last):
  File "/usr/local/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/local/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/local/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.280 was not provided by any .service files
```

**Comment by cutalion** [comment]
![dfeet exec overview](https://cloud.githubusercontent.com/assets/103887/11085410/112aa7a6-8857-11e5-8481-f1b91f849c5a.png)

**Comment by igorsantos07** [comment]
When installing the 2.0 RC .deb on Linux Mint 16 MATE I got this:
```
 ~  hamster 
Traceback (most recent call last):
  File "/usr/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ImportError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/hamster-applet/hamster-windows-service", line 38, in overview
  File "/usr/lib/python2.7/dist-packages/hamster/configuration.py", line 106, in show
  File "/usr/lib/python2.7/dist-packages/hamster/configuration.py", line 132, in get_overview_class
  File "/usr/lib/python2.7/dist-packages/hamster/overview.py", line 28, in <module>
    from gi.repository import Gtk as gtk
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 27, in <module>
    from ._gi import _API
ImportError: cannot import name _API
```

**Comment by dyson** [comment]
Same error as OP installing 2.0-rc1 on Ubuntu 15.10 from deb.

**Comment by rangermeier** [comment]
Same issue on Fedora 23: Updated to [hamster-time-tracker-2.0-0.2.rc1.fc23](http://arm.koji.fedoraproject.org/koji/buildinfo?buildID=337716) and now hamster doesn't start anymore.

```
[ranger@tp ~]$ hamster
/usr/lib/python2.7/site-packages/hamster/lib/stuff.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
/usr/lib/python2.7/site-packages/hamster/lib/configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf as gconf
Traceback (most recent call last):
  File "/usr/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.221 was not provided by any .service files
```

**Comment by FelixSchwarz** [comment]
@rangermeier Please open a Fedora bug report about this. Seems to be a serious issue and I'm really not thrilled to see this major update (even more so as this is just labeled as "rc" by upstream here) in a stable Fedora.
(However I have to blame myself in not spending time to intervene when the update was in bodhi.)

**Comment by FelixSchwarz** [comment]
@rangermeier Well, the update hit Fedora stable now and we have the first report already in. If you're interested in Fedora workarounds + progress in Fedora please subscribe to https://bugzilla.redhat.com/show_bug.cgi?id=1307253

**Comment by FelixSchwarz** [comment]
If you experience the issue, can you try the latest hamster git (or manually change 4 lines of code as shown in d869f7da0eec48df1f52771fed8ed12b12fbab61 , see #254 ). That should fix the issue for now.

**Comment by FelixSchwarz** [comment]
@gsmetal Hamster git contains a workaround. If you installed the software via ubuntu please file an Ubuntu report and point them to #254. If you installed hamster manually please update to the latest git.
