### ISSUE TITLE
Unable to run on Debian 8

### ISSUE THREAD

**Issue by PayasR** [projecthamster/hamster#278]
I installed hamster from the hamster_stable branch, but i get this error on startup:

Traceback (most recent call last):
  File "/usr/local/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/local/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/local/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.KeyError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/hamster-time-tracker/hamster-windows-service", line 38, in overview
    def overview(self): dialogs.overview.show(self.app)
  File "/usr/local/lib/python2.7/dist-packages/hamster/lib/configuration.py", line 149, in show
    dialog = self.get_dialog_class()(parent, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hamster/overview.py", line 395, in __init__
    self.fact_tree = FactTree()
  File "/usr/local/lib/python2.7/dist-packages/hamster/widgets/facttree.py", line 219, in __init__
    self.date_label = Label(10, 3)
  File "/usr/local/lib/python2.7/dist-packages/hamster/widgets/facttree.py", line 59, in __init__
    self.layout = pangocairo.create_layout(self._label_context)
KeyError: 'could not find foreign type Context'

**Comment by PayasR** [comment]
Apparently I was missing python-gi-cairo package on my system. @toupeira please add this in the README.md

Similar issue here:
Ref: https://github.com/jflesch/paperwork/issues/283
