### ISSUE TITLE
ZeroDivisionError on startup

### ISSUE THREAD

**Issue by simeonackermann** [projecthamster/hamster#304]
Hamster start fails with following message:

> Traceback (most recent call last):
  File "/usr/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ZeroDivisionError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 826, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/bin/hamster-windows-service", line 38, in overview
    def overview(self): dialogs.overview.show(self.app)
  File "/usr/lib/python2.7/site-packages/hamster/lib/configuration.py", line 149, in show
    dialog = self.get_dialog_class()(parent, **kwargs)
  File "/usr/lib/python2.7/site-packages/hamster/overview.py", line 417, in __init__
    self.find_facts()
  File "/usr/lib/python2.7/site-packages/hamster/overview.py", line 455, in find_facts
    self.totals.set_facts(self.facts)
  File "/usr/lib/python2.7/site-packages/hamster/overview.py", line 305, in set_facts
    self.stacked_bar.set_items([(cat, delta.total_seconds() / 60.0) for cat, delta in totals['category']])
  File "/usr/lib/python2.7/site-packages/hamster/overview.py", line 136, in set_items
    res.append((key, val, val * 1.0 / max_value))
ZeroDivisionError: float division by zero

OS is Fedora 22, Gnome 3.16.2

**Comment by FelixSchwarz** [comment]
duplicate of #245  / should be fixed by #296

**Comment by simeonackermann** [comment]
Yep
