### ISSUE TITLE
KeyError: 'could not find foreign type Context'

### ISSUE THREAD

**Issue by shihrer** [projecthamster/hamster#320]
Built/install from source on Ubuntu 16.04 with Gnome 3.18.  Attempting to launch hamster gives me this:

```
/usr/lib/python2.7/dist-packages/hamster/lib/configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf as gconf
Traceback (most recent call last):
  File "/usr/bin/hamster", line 391, in <module>
    getattr(hamster_client, command)(*args)
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.KeyError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/hamster-time-tracker/hamster-windows-service", line 38, in overview
    def overview(self): dialogs.overview.show(self.app)
  File "/usr/lib/python2.7/dist-packages/hamster/lib/configuration.py", line 149, in show
    dialog = self.get_dialog_class()(parent, **kwargs)
  File "/usr/lib/python2.7/dist-packages/hamster/overview.py", line 395, in __init__
    self.fact_tree = FactTree()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/facttree.py", line 219, in __init__
    self.date_label = Label(10, 3)
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/facttree.py", line 59, in __init__
    self.layout = pangocairo.create_layout(self._label_context)
KeyError: 'could not find foreign type Context'
```
Am I missing a dependency?

**Comment by shihrer** [comment]
Resolved this, was missing python-gi-cairo.  Now I'm getting:

`/usr/lib/python2.7/dist-packages/hamster/lib/stuff.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
/usr/lib/python2.7/dist-packages/hamster/lib/configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf as gconf
Traceback (most recent call last):
  File "/usr/bin/hamster", line 387, in <module>
    hamster_client.overview()
  File "/usr/bin/hamster", line 152, in overview
    self._launch_window("overview")
  File "/usr/bin/hamster", line 143, in _launch_window
    getattr(server, window_name)()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.900 was not provided by any .service files
`

**Comment by shihrer** [comment]
Seems to be working.  After getting python-gi-cairo, I uninstalled, did a ./waf clean on the directory, and then rebuilt and installed.  So I guess I'll close this.  Not sure what was causing the second error.

**Comment by skwerlman** [comment]
For others (like myself) who hit this on Gentoo, te package name is `dev-python/pygobject-cairo`
