### ISSUE TITLE
cannot import name client

### ISSUE THREAD

**Issue by Kudlaty01** [projecthamster/hamster#343]
After migrating from hamster-applet and building the new version from the source using the README.md instructions, then rebuilding with python-gi-cairo installed, and then installing python3-gi-cairo, removing python-gi-cairo and rebuilding the project on execution of hamster I receive a following message:
```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
ImportError: cannot import name client
```
I receive the same message after uninstalling the built version and replacing it with a stable .deb package and even on replacing everything with hamster-applet from Debian Jessie packages repo.
Might it have something to do with the directories structure?
I am not an advanced python developer, so please forgive me if it is just my fault, but I have searched internet for some answers but none of them addressed this specific package importing. I would like to ask for help how can I get things back to work as they did.

**Comment by Kudlaty01** [comment]
I have also noticed that thile in the /usr/lib/python2.7/dist-packages/hamster directory in the python interpreter after manual import of client I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "client.py", line 27, in <module>
    from hamster.lib import trophies
ImportError: cannot import name trophies
```
When in the lib directory I can import trophies manually into the interpreter without any problems

**Comment by Kudlaty01** [comment]
I have found out that hamster package modules cannot be seen among others in the dist-packages.
I can also add that I have naively run the setup.py script. May that be the problem cause? If so, what could be the solution?

**Comment by Kudlaty01** [comment]
It seems it finds the package itself, as PyCharm peeks into the /usr/lib/python2.7/dist-packages/hamster/__init__.py (it's empty), but does not find anything about the .py scripts in the same directory

**Comment by Kudlaty01** [comment]
Removing any occurrence of hamster from the system and reinstallation of the whole package fixed the issue
