### ISSUE TITLE
Problem with list viewing

### ISSUE THREAD

**Issue by Kudlaty01** [projecthamster/hamster#344]
While trying to run `hamster list` I receive the following error message:
```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 391, in <module>
    getattr(hamster_client, command)(*args)
  File "/usr/bin/hamster", line 254, in list
    self._list(start_time, end_time)
  File "/usr/bin/hamster", line 313, in _list
    print fact_line.format(**headers)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0119' in position 7: ordinal not in range(128)
```
I would be very grateful for any clue how could I fix thix

**Comment by ederag** [comment]
Thanks for the report.
This looks like an utf-8 issue, hopefully solved in [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1)
