### ISSUE TITLE
TypeError on export multiple days report

### ISSUE THREAD

**Issue by ederag** [projecthamster/hamster#384]
With current master (843f363), selecting multiple days to overview, and
exporting an html report yield
```python
Traceback (most recent call last):
  File "/home/ederag/share/prog/python/hamster/src/hamster/overview.py", line 538, in on_report_chosen
    reports.simple(self.facts, start, end, format, path)
  File "/home/ederag/share/prog/python/hamster/src/hamster/reports.py", line 61, in simple
    writer.write_report(facts)
  File "/home/ederag/share/prog/python/hamster/src/hamster/reports.py", line 92, in write_report
    self._finish(facts)
  File "/home/ederag/share/prog/python/hamster/src/hamster/reports.py", line 287, in _finish
    while date <= self.end_date:
TypeError: can't compare datetime.datetime to datetime.date 
```
That does not happen when a single day is shown.

**Comment by ederag** [comment]
Should be fixed with 7f527368d7b0debe2678c1ea3e021f85479c8be2.
