### ISSUE TITLE
src/hamster-service fails when there is no hamster.db

### ISSUE THREAD

**Issue by ederag** [projecthamster/hamster#394]
```bash
src/hamster-service &
```
```python
hamster-service up
Traceback (most recent call last):
  File "src/hamster-service", line 305, in <module>
    storage = Storage(loop)
  File "src/hamster-service", line 51, in __init__
    db.Storage.__init__(self, _("Unsorted"))
  File "/media/sf_python/hamster/src/hamster/storage/db.py", line 68, in __init__
    self.db_path = self.__init_db_file(database_dir)
  File "/media/sf_python/hamster/src/hamster/storage/db.py", line 142, in __init_db_file
    copyfile(os.path.join(data_dir, 'hamster.db'), db_path)
  File "/usr/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/media/sf_python/hamster/src/data/hamster.db'
```

Tested with current master, d86e07fc6550f53713917d6308584400c8bdbbc3
```bash
git describe --abbrev=40 --always --dirty=+
v2.0-118-gd86e07fc6550f53713917d6308584400c8bdbbc3
```

It looks like #61, except that it happens for the dev version, without installation.

**Comment by ederag** [comment]
Hopefully fixed by #395
