### ISSUE TITLE
migrate to Gtk.Application broke stuff

### ISSUE THREAD

**Issue by fantasai** [projecthamster/hamster#529]
Sorry, I don't understand what happened, but I can run 8d281b966a265b8a4344e266f0456c2a85fcc45d but not d22abc46333f0825fc8aef59fecd0b5b0ca79d31 or any later revisions.

Here is the error report:
```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 450, in <module>
    app.register()
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: DescribeAll is not a valid method of interface org.gtk.Actions
 (19)
```

**Comment by ederag** [comment]
#526 ?
