### ISSUE TITLE
OverflowError on long-running desktop

### ISSUE THREAD

**Issue by ederag** [projecthamster/hamster#555]
```python
Traceback (most recent call last):
  File "/usr/bin/hamster", line 137, in on_activate_window
    self._open_window(action.get_name(), data)
  File "/usr/bin/hamster", line 176, in _open_window
    controller.present()
  File "/usr/lib/python3.6/site-packages/hamster/lib/configuration.py", line 94, in present
    self.window.present_with_time(glib.get_monotonic_time() / 1000)
OverflowError: 5591403785 not in range 0 to 4294967295
```
This happens on a system not rebooted in more than `4294967295 / (24*3600*1e3) =  49.7 days`
This can be checked with 

```bash
uptime && hamster
 13:11:06  up 64 days 17:37,  4 users,  load average: 0.28, 0.35, 0.45
...
OverflowError: 5593037826 not in range 0 to 4294967295
```

**Comment by mwilck** [comment]
This is really amazing, the "time" field in Gdk timestamps seems to be an `uint32` measuring time since boot in milliseconds. Not sure how this has ever worked.

As a workaround, I guess you can pass 0, or (x % 0xffffffff), or simply call `self.window.present()`.

**Comment by mwilck** [comment]
@ederag, I saw you comment on (https://gitlab.gnome.org/GNOME/gtk/issues/624)[gtk#24], so it seems you've been researching along similar lines as I did :smile: 

My conclusion from what I've found so far is that these timestamps are only meant to be **relative**, without a defined base. Using `(x % 0xffffffff) or 1` should be fine (the `or 1`  would avoid passing 0, which would fail on wayland).

**Comment by ederag** [comment]
Thanks, it works. I'll file a PR with the tested file soon.

**Comment by mwilck** [comment]
Lest you fall into the same trap that I just fell in, this would work:

        tm = (glib.get_monotonic_time() // 1000) & 0xffffffff or 1
        self.window.present_with_time(tm)

**Comment by mwilck** [comment]
@ederag, taking one step back, I wonder about your commit d22abc46333f ("migrate to Gtk.Application") where you introduced the `present_with_time()` call. You have `present()` methods in various dialogs, but you applied the workaround for  [Gtk#624](https://gitlab.gnome.org/GNOME/gtk/issues/624) only in `configuration.py`. If this isn't necessary for the other dialogs, why here? IMO you'd be better off by just reverting back to `self.window.present()` in `configuration.py`.

While reading through the lengthy discussions between Gtk developers on this subject, I've come to the conclusion that it's dangerous to assume that Gtk time stamps can be synthesized using `glib.get_monotonic_time()//1000`. It happens to work today, but using it means to rely on undocumented behavior. If you really need a time stamp in `Controller.present()`, it's better to use `Gtk.get_current_event_time()`, which would return a valid Gtk time stamp if Gtk is currently processing an event (which should be the case when `Controller.present()` is being called).

Just a suggestion.
