### ISSUE TITLE
Exception against NameHasNoOwner crashes program

### ISSUE THREAD

**Issue by fantasai** [projecthamster/hamster#566]
https://github.com/projecthamster/hamster/issues/529 seems to have been fixed, but now running into

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.gnome.Hamster': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/hamster", line 138, in on_activate_window
    self._open_window(action.get_name(), data)
  File "/usr/bin/hamster", line 168, in _open_window
    self.overview_controller = Overview()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 479, in __init__
    self.find_facts()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 533, in find_facts
    self.facts = self.storage.get_facts(start, end, search_terms=search)
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 156, in get_facts
    for fact in self.conn.GetFactsJSON(dbus_range, search_terms)]
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 97, in conn
    '/org/gnome/Hamster'),
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Hamster exited with status 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.gnome.Hamster': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/hamster", line 138, in on_activate_window
    self._open_window(action.get_name(), data)
  File "/usr/bin/hamster", line 168, in _open_window
    self.overview_controller = Overview()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 479, in __init__
    self.find_facts()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 533, in find_facts
    self.facts = self.storage.get_facts(start, end, search_terms=search)
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 156, in get_facts
    for fact in self.conn.GetFactsJSON(dbus_range, search_terms)]
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 97, in conn
    '/org/gnome/Hamster'),
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Hamster exited with status 1
```

This is running 95687ac640caa8e31e7468a052d15328b32891b5 after executing the following:
```
☯ ~$ pkill -f hamster-service
☯ ~$ pkill -f hamster-windows-service
☯ ~$ pgrep -af hamster
☯ ~$ sudo ./waf uninstall
☯ ~$ cd temporary/hamster
☯ ~/temporary/hamster$ sudo ./waf uninstall
☯ ~/temporary/hamster$ ./waf configure build
☯ ~/temporary/hamster$ ( umask 0022 && sudo ./waf install; )
☯ ~/temporary/hamster$ hamster
```

I haven't bisected the commits to find the responsible commit, but as before, https://github.com/projecthamster/hamster/commit/8d281b966a265b8a4344e266f0456c2a85fcc45d builds and runs correctly.

**Comment by ederag** [comment]
Maybe #549, hopefully ?

**Comment by mwilck** [comment]
This error would occur if `hamster-service` (which owns `org.gnome.Hamster`) had exited or crashed. @fantasai, check if you can start the service manually, either by running `hamster-service &` or by activating `org.gnome.Hamster` e.g. with d-feet. Also, check your logs for DBus error messages (`journalctl --user`).

> Looks a lot like [#402 (comment)](https://github.com/projecthamster/hamster/issues/402#issuecomment-525253222).

Not quite. in #402, it was `hamster-windows-service` which failed to start. Here, it's `hamster-service`.

**Comment by ederag** [comment]
@fantasai Please just follow https://github.com/projecthamster/hamster/issues/566#issuecomment-587315180 and report back success or failure. We'll see then.

**Comment by ederag** [comment]
@fantasai Closing because this could scare packagers away for nothing,
but please report either way, I'd really like to have an answer before the v3.0 release.
