### ISSUE TITLE
Version is not a valid method of interface org.gnome.Hamster

### ISSUE THREAD

**Issue by fantasai** [projecthamster/hamster#621]
Tried to update to the latest again. As [before](https://github.com/projecthamster/hamster/issues/566), followed README instructions and ran

```
pkill -f hamster-service
pkill -f hamster-windows-service
./waf configure build
( umask 0022 && sudo ./waf install; )
```

Running `hamster` now results in

```
Traceback (most recent call last):
  File "/usr/bin/hamster", line 149, in on_activate_window
    self._open_window(action.get_name(), data)
  File "/usr/bin/hamster", line 184, in _open_window
    self.overview_controller = Overview()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 477, in __init__
    self.find_facts()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 531, in find_facts
    self.facts = self.storage.get_facts(start, end, search_terms=search)
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 156, in get_facts
    for fact in self.conn.GetFactsJSON(dbus_range, search_terms)]
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 99, in conn
    server_version = self._connection.Version()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: Version is not a valid method of interface org.gnome.Hamster

Traceback (most recent call last):
  File "/usr/bin/hamster", line 149, in on_activate_window
    self._open_window(action.get_name(), data)
  File "/usr/bin/hamster", line 184, in _open_window
    self.overview_controller = Overview()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 477, in __init__
    self.find_facts()
  File "/usr/lib/python3/dist-packages/hamster/overview.py", line 531, in find_facts
    self.facts = self.storage.get_facts(start, end, search_terms=search)
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 156, in get_facts
    for fact in self.conn.GetFactsJSON(dbus_range, search_terms)]
  File "/usr/lib/python3/dist-packages/hamster/client.py", line 99, in conn
    server_version = self._connection.Version()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: Version is not a valid method of interface org.gnome.Hamster
```

Reverting back to 8d281b9 again, which is the last version I managed to get to run. :/

**Comment by mwilck** [comment]
`Version()` has been defined in `org.gnome.Hamster` since 03adc01. You still seem to have hamster-service from an old version running.

**Comment by fantasai** [comment]
I did run the kill commands as described above? But anyway, whatever the reason, the August 7th build seems to work, so closing. :)
