### ISSUE TITLE
Can't move an activity into another category

### ISSUE THREAD

**Issue by lalejand** [projecthamster/hamster#632]
In tracking settings, "categories ans tags" tab, when I finish a project I used to d&d the activity to another category in order to separate ongoing projects and finished projects.
I used to do that with the old hamster applet. Since I installed the new one, via snap, I can't do that anymore.
Please enable this functionality :)
![image](https://user-images.githubusercontent.com/30934848/96372448-18c80f00-1167-11eb-9afb-e1584b32ff26.png)
In that example, if I d&d the highlighted activity (it as a finished project) on the "archives Odigi" category nothing happens. It should change the category of the activity.

**Comment by lalejand** [comment]
Is there a possibility to fix that?

**Comment by lalejand** [comment]
When I try to D&D an activity into another category, I get those errors: 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 222, in on_category_list_drag_motion
    if drop_position != gtk.TREE_VIEW_DROP_AFTER and \
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'TREE_VIEW_DROP_AFTER'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 192, in drag_data_get_data
    selection.set(selection.target, 0, str(data))
                  ^^^^^^^^^^^^^^^^
AttributeError: 'SelectionData' object has no attribute 'target'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hamster/preferences.py", line 231, in on_category_drop
    data = selection.data
           ^^^^^^^^^^^^^^
AttributeError: 'SelectionData' object has no attribute 'data'
