### ISSUE TITLE
Flatpak Issue: DBus.Error.NameHasNoOwner, DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by ziswiler** [projecthamster/hamster#654]
I tried building and running hamster as a flatpak on Fedora Silverblue 32 but I keep getting below error. Does anybody know what exactly is going wrong?

```
[user@host ~]$ flatpak run org.gnome.Hamster
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/app/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/hamster", line 149, in on_activate_window
    self._open_window(action.get_name(), data)
  File "/app/bin/hamster", line 184, in _open_window
    self.overview_controller = Overview()
  File "/app/lib/python3.7/site-packages/hamster/overview.py", line 477, in __init__
    self.find_facts()
  File "/app/lib/python3.7/site-packages/hamster/overview.py", line 531, in find_facts
    self.facts = self.storage.get_facts(start, end, search_terms=search)
  File "/app/lib/python3.7/site-packages/hamster/client.py", line 156, in get_facts
    for fact in self.conn.GetFactsJSON(dbus_range, search_terms)]
  File "/app/lib/python3.7/site-packages/hamster/client.py", line 97, in conn
    '/org/gnome/Hamster'),
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/app/lib/python3.7/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/app/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/app/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/hamster", line 149, in on_activate_window
    self._open_window(action.get_name(), data)
  File "/app/bin/hamster", line 184, in _open_window
    self.overview_controller = Overview()
  File "/app/lib/python3.7/site-packages/hamster/overview.py", line 477, in __init__
    self.find_facts()
  File "/app/lib/python3.7/site-packages/hamster/overview.py", line 531, in find_facts
    self.facts = self.storage.get_facts(start, end, search_terms=search)
  File "/app/lib/python3.7/site-packages/hamster/client.py", line 156, in get_facts
    for fact in self.conn.GetFactsJSON(dbus_range, search_terms)]
  File "/app/lib/python3.7/site-packages/hamster/client.py", line 97, in conn
    '/org/gnome/Hamster'),
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/app/lib/python3.7/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.7/site-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/app/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

**Comment by matthijskooijman** [comment]
Hm, that exception suggests to me (but I'm guessing here) that maybe the flatpak has no access to the dbus metadata files, or maybe no access to the dbus at all?

@tchernobog, any idea?

**Comment by tchernobog** [comment]
Sorry, I completely overlooked this. The email notification must have ended in my spam folder.
The manifest explicitly grants ownership to the app to these DBus names:

`org.gnome.Hamster`, `org.gnome.Hamster.GUI`, `org.gnome.Hamster.WindowServer`.

Can you confirm that there isn't another Hamster process already running on your system?

**Comment by matthijskooijman** [comment]
@ziswiler, did you see the question above? Can you confirm>

**Comment by ziswiler** [comment]
> Can you confirm that there isn't another Hamster process already running on your system?

Yes, sorry, no other Hamster process anywhere.

Anyway, I meanwhile upgraded to Fedora Silverblue 33 and re-built the Hamster Flatpak and now it just works! Awesome, thanks guys!
