### ISSUE TITLE
Error while launching kazam on garuda linux based on arch

### ISSUE THREAD

**Issue by Siddiq9710** [projecthamster/hamster#668]
**when ever i launch kazam in garuda linux i get the following error

 #`WARNING Kazam - Failed to correctly detect operating system.
Traceback (most recent call last):
  File "/usr/bin/kazam", line 148, in <module>
    from kazam.app import KazamApp
  File "/usr/lib/python3.9/site-packages/kazam/app.py", line 35, in <module>
    from kazam.backend.prefs import *
  File "/usr/lib/python3.9/site-packages/kazam/backend/prefs.py", line 26, in <module>
    from xdg.BaseDirectory import xdg_config_home
ModuleNotFoundError: No module named 'xdg.BaseDirectory`

**Comment by GeraldJansen** [comment]
This looks like spam because it has nothing to do with Hamster.

**Comment by Siddiq9710** [comment]
![Uploading 16128925255824095406909328604253.jpg…]()
