### ISSUE TITLE
Submit the application to FlatHub as well

### ISSUE THREAD

**Issue by rabin-io** [projecthamster/hamster#688]
I stared an App Submission process with flathub, you are welcome to take over anytime.

flathub/flathub#2614

**Comment by rabin-io** [comment]
approved https://github.com/flathub/flathub/pull/2636
and it's available on FlatHub now, https://flathub.org/apps/details/org.gnome.Hamster

**Comment by mattdrepo** [comment]
flatpak run org.gnome.Hamster
Traceback (most recent call last):
  File "/app/bin/hamster", line 40, in <module>
    from hamster import client, reports
  File "/app/lib/python3.9/site-packages/hamster/reports.py", line 33, in <module>
    from hamster.lib.configuration import runtime
  File "/app/lib/python3.9/site-packages/hamster/lib/configuration.py", line 128, in <module>
    runtime = RuntimeStore()
  File "/app/lib/python3.9/site-packages/hamster/lib/configuration.py", line 124, in __init__
    self.storage = Storage()
  File "/app/lib/python3.9/site-packages/hamster/client.py", line 79, in __init__
    self.bus = dbus.SessionBus()
  File "/app/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/app/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

**Comment by mattdrepo** [comment]
resolved with
 export $(dbus-launch)
before launching hamster from cli

**Comment by aquaherd** [comment]
May I close this issue, then?
