### ISSUE TITLE
Fails to start, No module named 'dbus.mainloop.glib'

### ISSUE THREAD

**Issue by mizzunet** [projecthamster/hamster#691]
Hamster fails to start on Arch Linux.

```
 ~  hamster 
Traceback (most recent call last):
  File "/usr/bin/hamster", line 40, in <module>
    from hamster import client, reports
  File "/usr/lib/python3.9/site-packages/hamster/client.py", line 33, in <module>
    from hamster.lib.dbus import (
  File "/usr/lib/python3.9/site-packages/hamster/lib/dbus.py", line 3, in <module>
    from dbus.mainloop.glib import DBusGMainLoop as DBusMainLoop
ModuleNotFoundError: No module named 'dbus.mainloop.glib'
```

`python-dbus` has been installed

**Comment by mwilck** [comment]
Missing the python 3.9 dbus module, perhaps?

**Comment by mwilck** [comment]
Thanks for the feedback!
