### ISSUE TITLE
exceptions on Fedora 35

### ISSUE THREAD

**Issue by mattdrepo** [projecthamster/hamster#694]
running flatpak run org.gnome.Hamster

gives these exceptions:

Traceback (most recent call last):
  File "/app/bin/hamster", line 40, in <module>
    from hamster import client, reports
  File "/app/lib/python3.9/site-packages/hamster/reports.py", line 33, in <module>
    from hamster.lib.configuration import runtime
  File "/app/lib/python3.9/site-packages/hamster/lib/configuration.py", line 128, in <module>
    runtime = RuntimeStore()
  File "/app/lib/python3.9/site-packages/hamster/lib/configuration.py", line 124, in __init__
    self.storage = Storage()
  File "/app/lib/python3.9/site-packages/hamster/client.py", line 79, in __init__
    self.bus = dbus.SessionBus()
  File "/app/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/app/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

Do I need to be doing something specifically for Hamster on this Fedora release?

Have noticed some issues reported with DBUS on later releases of Ubuntu - disabling allowing the application to run?  My python version is much later than this log, is python the cause or is access via DBUS an issue, or both?

Any help appreciated!

**Comment by mattdrepo** [comment]
resolved with
 export $(dbus-launch)
before launching hamster from cli

**Comment by aquaherd** [comment]
OP has resolved.
