### ISSUE TITLE
pyxdg changed api

### ISSUE THREAD

**Issue by faebser** [projecthamster/hamster#711]
When I run hamster from the comand line, I get the following error:

```python
Traceback (most recent call last):
  File "/usr/bin/hamster", line 40, in <module>
    from hamster import client, reports
  File "/usr/lib/python3.10/site-packages/hamster/reports.py", line 33, in <module>
    from hamster.lib.configuration import runtime
  File "/usr/lib/python3.10/site-packages/hamster/lib/configuration.py", line 29, in <module>
    from xdg.BaseDirectory import xdg_data_home
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
```

It seems that the`pyxdg==0.28` seems to have changed the API to access the BaseDirectory

**Comment by faebser** [comment]
While trying to setup a dev enviorment I created a virtualenv to run hamster inside with the following packages:
`
dbus-python==1.3.2
pgi==0.0.11.2
pycairo==1.21.0
PyGObject==3.42.2
pyxdg==0.28
`
and it ran without a problem, so it seems that the problem is related to my environment. I'm running arch linux and installed both hamster and python-xdg with pacman.

**Comment by faebser** [comment]
It seems that I had both pyxdg==0.28 and xdg==5.1.1 installed which lead to xdg shadowing pyxdg, leading to the error.
