### ISSUE TITLE
Tool not starting with newer pthon versions

### ISSUE THREAD

**Issue by ma-adrian** [projecthamster/hamster#726]
Hi, the tool is not starting with newer python versions because `bind_textdomain_codeset` was removed from i18n:
```
~ >>> hamster                                                                   

(hamster:3525): Gtk-WARNING **: 09:02:59.518: Theme parsing error: gtk.css:2:19: 'solid' is not a valid color name
Traceback (most recent call last):
  File "/usr/bin/hamster", line 415, in <module>
    i18n.setup_i18n()
  File "/usr/lib/python3.11/site-packages/hamster/lib/i18n.py", line 24, in setup_i18n
    module.bind_textdomain_codeset('hamster','utf8')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gettext' has no attribute 'bind_textdomain_codeset'
```

**Comment by mwilck** [comment]
This is fixed in current master (b155ad5)
